### ISSUE TITLE
Integrate entity map to content state (draftjs 0.11 like)

### ISSUE THREAD

**Issue by aight8** [webstronauts/draft-php#6]
Integrate entity map methods to content state class.
So we can remove DraftEntity with it's global entity map and key counter.
In draftjs 0.11 this becomes standard anyway. No BCB with older states anyway since it's only affects the architecture.

**Comment by robinvdvleuten** [comment]
@aight8 this is now merged with your PR right?

**Comment by aight8** [comment]
Yep. However I will rename __setEntity and __removeEntity because they are no Immutable classes.

**Comment by aight8** [comment]
Renamed in #13 
After this, this issue can be closed
