### ISSUE TITLE
Basic data type & raw input structure validation

### ISSUE THREAD

**Issue by aight8** [webstronauts/draft-php#7]
There are some point of validation which this repo should ensure (mainly data type & structure validations), in convertFromRaw method:

- [x] valid mutability on entity
- [x] depth must be an integer equal or greater than zero (otherwise set 0)
- [x] if entity not found in entityRange throw an exception (instead php error because there is no check)
- [x] offset >= 0, length >= 1 (in inlineStyleRanges and entityRanges)
- [x] all other raw structure checks (is_array etc.)
- [x] content block props key, text and draft entity type should be a string

Otherwise throw an exception.

**Comment by aight8** [comment]
Implemented in the main PR currently: #4

**Comment by robinvdvleuten** [comment]
PR #4 is merged, so this one can be closed
